manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: Scybin
      url-base: https://github.com/Scybin
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-keyboards-scyboard
      remote: Scybin
      revision: main
  self:
    path: config
